# Generated by Django 3.2.7 on 2021-09-27 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='mail_address',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('requester_name', models.CharField(max_length=15)),
                ('requester_mail_address', models.EmailField(max_length=254)),
                ('message', models.CharField(default=None, max_length=100)),
                ('start_at', models.DateField()),
                ('end_at', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_accepted', models.BooleanField()),
                ('admin_message', models.CharField(default=None, max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarapp.user')),
            ],
        ),
    ]
