# Generated by Django 3.2.7 on 2021-09-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_auto_20210927_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='admin_message',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='message',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
