# Generated by Django 3.2.7 on 2021-09-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_auto_20210929_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='request_id',
        ),
        migrations.AddField(
            model_name='request',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
