# Generated by Django 3.2.7 on 2021-10-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0005_auto_20210929_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='end_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='is_accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='start_at',
            field=models.DateTimeField(),
        ),
    ]
