# Generated by Django 3.2.7 on 2021-10-07 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0007_calendar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='user_id',
            new_name='user',
        ),
    ]
