# Generated by Django 3.2.7 on 2021-10-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0008_auto_20211007_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='title',
            field=models.CharField(default='default', max_length=15),
            preserve_default=False,
        ),
    ]
